### ISSUE TITLE
Class 'Kasterweb_Tnt_Api' not found

### ISSUE THREAD

**Issue by caiosiqueira14** [luanalves/magento_tnt#1]
Luan,
A classe Kasterweb_Tnt_Api que está sendo utilizada em (app/code/local/Kasterweb/Tnt/Model/Api.php on line 13), não existe no módulo.

O que gera um erro PHP.

**Comment by luanalves** [comment]
@caiosiqueira14 o ajuste foi realizado. 
Terá de remover todo o conteúdo do diretório app/code/local/Kasterweb/ , porque o diretório do módulo ficou o community.
